load("@io_bazel_rules_python//python:python.bzl", "py_library")


py_library(
    name = "utils",
    deps = [
        '//kglib/utils/grakn',
        '//kglib/utils/graph',
        '//kglib/utils/test'
    ],
    visibility=['//visibility:public']
)