load("@io_bazel_rules_python//python:python.bzl", "py_library")
load("@pypi_dependencies//:requirements.bzl", "requirement")


py_library(
    name = "type",
    srcs = [
        'type.py',
    ],
    visibility=['//visibility:public']
)