define

example-id sub attribute,
    value long;

age sub attribute,
    value long;

name sub attribute,
    value string;

severity sub attribute,
    value double;

units-per-week sub attribute,
    value long;

person sub entity,
    owns example-id @key,
    owns age,
    plays diagnosis:patient,
    plays diagnosis:doctor,
    plays candidate-diagnosis:candidate-patient,
    plays symptom-presentation:symptomatic-patient,
    plays consumption:consumer,
    plays risk-factor:person-at-risk,
    plays parentship:parent,
    plays parentship:child;

disease sub entity,
    owns name @key,
    plays causality:cause,
    plays diagnosis:diagnosed-disease,
    plays candidate-diagnosis:candidate-diagnosed-disease,
    plays risk-factor:risked-disease;

substance sub entity,
    owns name @key,
    plays consumption:consumed-substance;

parentship sub relation,
    relates child,
    relates parent;

diagnosis sub relation,
    relates patient,
    relates diagnosed-disease,
    relates doctor,
    relates diagnoser,
    owns probability-exists,
    owns probability-non-exists,
    owns probability-preexists;

candidate-diagnosis sub relation,
    relates candidate-patient,
    relates candidate-diagnosed-disease;

probability-exists sub attribute,
    value double;

probability-non-exists sub attribute,
    value double;

probability-preexists sub attribute,
    value double;

kgcn sub entity,
	plays diagnosis:diagnoser;

rule where-no-diagnosis-add-candidate-diagnosis:
    when {
        $p isa person;
        $d isa disease;
        not{ (patient: $p, diagnosed-disease: $d) isa diagnosis; };
    } then {
        (candidate-patient: $p, candidate-diagnosed-disease: $d) isa candidate-diagnosis;
    };

causality sub relation,
    relates cause,
    relates effect;

symptom sub entity,
    owns name @key,
    plays symptom-presentation:presented-symptom,
    plays causality:effect;

symptom-presentation sub relation,
    owns severity,
    relates presented-symptom,
    relates symptomatic-patient;

risk-factor sub relation,
    relates person-at-risk,
    relates risked-disease;

consumption sub relation,
    owns units-per-week,
    relates consumer,
    relates consumed-substance;

#rule alcohol-risk-of-diabetes:
#when {
#    $p isa person;
#    $c(consumer: $p, consumed-substance: $s) isa consumption, owns units-per-week $u;
#    $u >= 10;
#    $s isa substance, owns name "Alcohol";
#    $d isa disease, owns name "Diabetes Type II";
#} then {
#	(person-at-risk: $p, risked-disease: $d) isa alcohol-risk-factor;
#};
#
#rule over-40-risk-of-diabetes:
#when {
#    $p isa person, owns age $a;
#    $a >= 40;
#    $d isa disease, owns name "Diabetes Type II";
#} then {
#	(person-at-risk: $p, risked-disease: $d) isa age-risk-factor;
#};
#
#rule heriditary-risk-of-diabetes:
#when {
#    $p isa person;
#    $parent isa person;
#    $cause(parent: $parent, child: $p) isa parentship;
#    $dia(patient: $parent, diagnosed-disease: $d) isa diagnosis;
#    $d isa disease, owns name "Diabetes Type II";
#} then {
#	(person-at-risk: $p, risked-disease: $d) isa hereditary-risk-factor;
#};
#
#
#rule smoking-risk-of-multiple-sclerosis:
#when {
#    $p isa person;
#    $c(consumer: $p, consumed-substance: $s) isa consumption, owns units-per-week $u;
#    $u >= 12;
#    $s isa substance, owns name "Cigarettes";
#    $d isa disease, owns name "Multiple Sclerosis";
#} then {
#	(person-at-risk: $p, risked-disease: $d) isa smoking-risk-factor;
#};
#
#hereditary-risk-factor sub risk-factor,
#    relates person-at-risk,
#    relates risked-disease;
#
#age-risk-factor sub risk-factor,
#    relates person-at-risk,
#    relates risked-disease;
#
#alcohol-risk-factor sub risk-factor,
#    relates person-at-risk,
#    relates risked-disease;
#
#smoking-risk-factor sub risk-factor,
#    relates person-at-risk,
#    relates risked-disease;
