load("@rules_python//python:defs.bzl", "py_library")
load("@pypi_dependencies//:requirements.bzl", "requirement")


py_library(
    name = "object",
    srcs = [
        'comparable.py',
        'thing.py',
    ],
    visibility=['//visibility:public']
)