load("@rules_python//python:defs.bzl", "py_library")


py_library(
    name = "kgcn",
    deps = [
        '//kglib/kgcn_tensorflow/examples/diagnosis',
        '//kglib/kgcn_tensorflow/learn',
        '//kglib/kgcn_tensorflow/models',
        '//kglib/kgcn_tensorflow/pipeline',
        '//kglib/kgcn_tensorflow/plot',
    ],
    visibility=['//visibility:public']
)