#load("@rules_python//python:defs.bzl", "py_test", "py_library")
#load("@vaticle_kglib_pip//:requirements.bzl",
#       vaticle_kglib_requirement = "requirement")
#
#py_test(
#    name = "encode_test",
#    srcs = [
#        "encode_test.py"
#    ],
#    deps = [
#        "pipeline"
#    ]
#)
#
#py_test(
#    name = "utils_test",
#    srcs = [
#        "utils_test.py"
#    ],
#    deps = [
#        "pipeline",
#        "//kglib/utils/graph/test"
#    ]
#)